version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - ./db:/var/lib/mysql

  app:
    build:
      context: ../app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
    depends_on:
      - db
