apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: app-container
      image: ghcr.io/ycchen12/app:latest
      ports:
        - containerPort: 3000
      env:
        - name: DB_HOST
          value: 127.0.0.1
    - name: db
      image: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: app
        - name: MYSQL_USER
          value: app
        - name: MYSQL_PASSWORD
<<<<<<< HEAD
          value: app
=======
          value: app
>>>>>>> 2618aa2c8ae7a08f843c4aac4582de94ce662ea0
